{% set name = "vscode-icons" %}
{% set version = "11.2.0" %}
{% set publisher = "vscode-icons-team" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b68a5c2ef5faba2fbb4ea2f11164350d878db679d03fd1062c593c19eb05c4ea

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - nodejs 12  # [not (osx and arm64)]
    - nodejs 15  # [osx and arm64]
    - code-server >=3.9
  run:
    - code-server >=1.40.2

test:
  commands:
    - code-server --list-extensions --show-versions | grep {{ publisher }}.{{ name }}@{{ version }}

about:
  home: https://github.com/vscode-icons/vscode-icons
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  summary: Icons for Visual Studio Code.

extra:
  recipe-maintainers:
    - conda-forge/code-server
