{% set name = "vscode-icons" %}
{% set version = "12.2.0" %}
{% set publisher = "vscode-icons-team" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 040d40356517dc8f78bfde3330575c981c8ae4e377a015a22910667d126818c2

build:
  number: 0
  skip: true  # [win or nodejs>=15]

requirements:
  host:
    - nodejs
    - code-server >=3.9
  run:
    - code-server >=3.9

test:
  commands:
    - code-server --list-extensions --show-versions | grep {{ publisher }}.{{ name }}@{{ version }}

about:
  home: https://github.com/vscode-icons/vscode-icons
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  summary: Icons for Visual Studio Code.

extra:
  recipe-maintainers:
    - conda-forge/code-server
    - fhoehle
