{% set name = "vscode-icons" %}
{% set version = "11.3.0" %}
{% set publisher = "vscode-icons-team" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 59eb5b9d5a4dcf9e937e9342767d9f72cf8bd1d8c6b141b6d8ab52d681398e44

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - nodejs 12  # [not (osx and arm64)]
    - nodejs 15  # [osx and arm64]
    - code-server >=3.9
  run:
    - code-server >=3.9

test:
  commands:
    - code-server --list-extensions --show-versions | grep {{ publisher }}.{{ name }}@{{ version }}

about:
  home: https://github.com/vscode-icons/vscode-icons
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  summary: Icons for Visual Studio Code.

extra:
  recipe-maintainers:
    - conda-forge/code-server
