conda_forge_output_validation: true
bot:
  automerge: true
os_version:
  linux_64: cos7
provider:
  linux_aarch64: azure
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
